configs: configs/datasets/renbody/renbody.yaml

dataloader_cfg: # we see the term "dataloader" as one word?
    dataset_cfg: &dataset_cfg
        data_root: data/renbody/0023_06
        images_dir: images_calib
        bounds: [[-0.7310, -0.7813, -0.9621], [ 0.5340, 0.9587, 0.9929]]

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
