configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/dnerf.yaml # network model configuration
    - configs/datasets/dnerf_synthetic/jumpingjacks.yaml # dataset usage configuration
    - configs/specs/white.yaml # white background

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
