dataloader_cfg:
    dataset_cfg: &dataset_cfg
        ratio: 1.0

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg

model_cfg:
    sampler_cfg:
        bounds: [[-1.3, -1.3, -1.3], [1.3, 1.3, 1.3]]
        white_bg: True
