configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/envgs.yaml # rtgs model configuration
    - configs/datasets/nerf-casting/compact.yaml # dataset usage configuration

model_cfg:
    supervisor_cfg:
        perc_loss_weight: 0.01
        perc_loss_start_iter: 45000 # less iterations for faster training

runner_cfg:
    epochs: 120

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
